import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { cookies } from "next/headers";
import getTranslations from "@/actions/get-translations";
import AppProvider from "./app-provider";
import getLoggedUser from "@/actions/get-logged-user";
import { Toaster } from "@/components/ui/sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const cookieStore = await cookies();
  const lang = cookieStore.get("lang")?.value || "vi"; // ngôn ngữ mặc định là "vi"
  const translations = await getTranslations(lang);

  const loggedUser = await getLoggedUser(); // bạn tự xử lý auth/token ở đây
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AppProvider translations={translations} loggedUser={loggedUser}>
        {children}
        </AppProvider>
        <Toaster richColors  />
      </body>
    </html>
  );
}
